"""AutoCAD Scripting Service for generating .SCR and AutoLISP (.LSP) automation files."""

import os
from typing import Dict, Any, List, Optional
from autocad_mcp.utils.helpers import validate_dxf_path


def generate_scr_script(
    commands: List[str],
    output_path: str,
    comment: str = "Generated by AutoCAD MCP",
) -> Dict[str, Any]:
    """
    Generate an AutoCAD Script file (.scr).
    In AutoCAD, .scr files contain sequential command line entries.
    Useful for batch processing (e.g. zoom extents, purge, export, drawing primitives).
    """
    abs_path = os.path.abspath(os.path.expanduser(output_path))
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)

    lines = [
        f";; {comment}",
        ";; Run in AutoCAD using: SCRIPT -> select this file",
        "",
    ]
    for cmd in commands:
        lines.append(cmd.strip())

    # SCR files require an empty newline at the end to execute the final command
    content = "\n".join(lines) + "\n"

    with open(abs_path, "w", encoding="utf-8") as f:
        f.write(content)

    return {
        "status": "success",
        "file_path": abs_path,
        "command_count": len(commands),
        "how_to_run": f"Open AutoCAD -> Type 'SCRIPT' -> Select '{os.path.basename(abs_path)}'",
    }


def generate_autolisp_script(
    routine_name: str,
    custom_lisp_code: Optional[str] = None,
    template_type: Optional[str] = None,
    parameters: Optional[Dict[str, Any]] = None,
    output_path: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate an AutoLISP (.lsp) routine file for AutoCAD automation.
    Supports built-in templates (batch_export_pdf, create_grid, draw_rectangle_with_dims, clean_drawing)
    or custom AutoLISP code.
    """
    params = parameters or {}
    clean_name = routine_name.strip().replace(" ", "_")

    if custom_lisp_code:
        lisp_content = f"""
;;; ==========================================================================
;;; AutoLISP Routine: {clean_name}
;;; Generated by AutoCAD MCP
;;; Load via AutoCAD: APPLOAD -> Choose this file -> Type 'c:{clean_name}'
;;; ==========================================================================

(defun c:{clean_name} ()
  (vl-load-com)
  (setvar "CMDECHO" 0)
  {custom_lisp_code}
  (setvar "CMDECHO" 1)
  (princ "\nDone!")
  (princ)
)
"""
    elif template_type == "clean_drawing":
        lisp_content = f"""
;;; Clean and Purge Drawing
(defun c:{clean_name} ()
  (vl-load-com)
  (setvar "CMDECHO" 0)
  (command "-PURGE" "ALL" "*" "N")
  (command "AUDIT" "Y")
  (command "ZOOM" "E")
  (setvar "CMDECHO" 1)
  (princ "\nDrawing purged and audited successfully!")
  (princ)
)
"""
    elif template_type == "create_grid":
        rows = int(params.get("rows", 5))
        cols = int(params.get("cols", 5))
        spacing_x = float(params.get("spacing_x", 100))
        spacing_y = float(params.get("spacing_y", 100))
        lisp_content = f"""
;;; Grid Generator Routine
(defun c:{clean_name} ()
  (vl-load-com)
  (setvar "CMDECHO" 0)
  (setq startPt '(0 0 0))
  (setq rows {rows})
  (setq cols {cols})
  (setq dx {spacing_x})
  (setq dy {spacing_y})

  ;; Draw Vertical Lines
  (setq c 0)
  (while (<= c cols)
    (setq x (* c dx))
    (command "LINE" (list x 0 0) (list x (* rows dy) 0) "")
    (setq c (1+ c))
  )

  ;; Draw Horizontal Lines
  (setq r 0)
  (while (<= r rows)
    (setq y (* r dy))
    (command "LINE" (list 0 y 0) (list (* cols dx) y 0) "")
    (setq r (1+ r))
  )

  (command "ZOOM" "E")
  (setvar "CMDECHO" 1)
  (princ "\nGrid generated successfully!")
  (princ)
)
"""
    elif template_type == "batch_export_pdf":
        lisp_content = f"""
;;; Quick PDF Export Routine
(defun c:{clean_name} ()
  (vl-load-com)
  (setvar "CMDECHO" 0)
  (command "-PLOT" "Y" "" "DWG To PDF.pc3" "ISO full bleed A3 (420.00 x 297.00 MM)" "M" "L" "N" "E" "F" "C" "Y" "acad.ctb" "Y" "N" "N" "N" "drawing_export.pdf" "N" "Y")
  (setvar "CMDECHO" 1)
  (princ "\nPDF export completed!")
  (princ)
)
"""
    else:
        # Default simple command template
        lisp_content = f"""
;;; AutoLISP Routine: {clean_name}
(defun c:{clean_name} ()
  (vl-load-com)
  (princ "\nRunning {clean_name}...")
  (princ "\nCompleted.")
  (princ)
)
"""

    if not output_path:
        output_path = f"{clean_name}.lsp"

    abs_path = os.path.abspath(os.path.expanduser(output_path))
    os.makedirs(os.path.dirname(abs_path), exist_ok=True)

    with open(abs_path, "w", encoding="utf-8") as f:
        f.write(lisp_content.strip() + "\n")

    return {
        "status": "success",
        "file_path": abs_path,
        "routine_name": clean_name,
        "command_to_run": f"Type 'APPLOAD' in AutoCAD, select {os.path.basename(abs_path)}, then type '{clean_name}'",
    }
