"""MCP Server 1: cad-file-mcp (Headless DXF/CAD File Engine)."""

from typing import Dict, Any, List, Optional, Union
from fastmcp import FastMCP
from autocad_mcp.services.dxf_reader import (
    get_dxf_summary,
    get_layers_info,
    get_blocks_info,
    query_entities,
    extract_texts,
)
from autocad_mcp.services.dxf_writer import (
    create_blank_drawing,
    add_layer,
    add_entities,
    delete_entities,
    execute_ezdxf_script,
)
from autocad_mcp.services.cad_scripting import (
    generate_scr_script,
    generate_autolisp_script,
)

mcp = FastMCP(
    name="cad-file-mcp",
    instructions="Headless CAD File Engine: inspect, create, edit DXF drawings, extract text/layers, and generate automation scripts without AutoCAD software.",
)


@mcp.tool()
def file_read_summary(file_path: str) -> Dict[str, Any]:
    """Get high-level summary of a DXF file (version, units, layer/block counts, bounding box)."""
    return get_dxf_summary(file_path)


@mcp.tool()
def file_list_layers(file_path: str) -> List[Dict[str, Any]]:
    """List all layers with color, linetype, lineweight, and on/frozen/locked status."""
    return get_layers_info(file_path)


@mcp.tool()
def file_list_blocks(file_path: str) -> List[Dict[str, Any]]:
    """List all block definitions and their instance counts."""
    return get_blocks_info(file_path)


@mcp.tool()
def file_query_entities(
    file_path: str,
    entity_type: Optional[str] = None,
    layer: Optional[str] = None,
    limit: int = 100,
    offset: int = 0,
) -> Dict[str, Any]:
    """Query drawing entities with filtering by type (e.g. LINE, CIRCLE, TEXT) and layer."""
    return query_entities(file_path, entity_type, layer, limit, offset)


@mcp.tool()
def file_extract_texts(file_path: str, layer: Optional[str] = None) -> List[Dict[str, Any]]:
    """Extract all text annotations and labels with coordinates and heights."""
    return extract_texts(file_path, layer)


@mcp.tool()
def file_create_drawing(
    file_path: str,
    dxf_version: str = "R2018",
    units: str = "mm",
    layers: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Create a new blank DXF CAD drawing file with units (mm, cm, m, in, ft)."""
    return create_blank_drawing(file_path, dxf_version, units, layers)


@mcp.tool()
def file_add_layer(
    file_path: str,
    name: str,
    color: Union[int, str] = 7,
    linetype: str = "CONTINUOUS",
    lineweight: Optional[int] = None,
    description: str = "",
) -> Dict[str, Any]:
    """Add or update a layer in DXF drawing."""
    return add_layer(file_path, name, color, linetype, lineweight, description)


@mcp.tool()
def file_add_entities(file_path: str, entities: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Batch add geometric entities (line, circle, arc, polyline, rectangle, text, dimension)."""
    return add_entities(file_path, entities)


@mcp.tool()
def file_delete_entities(
    file_path: str,
    handles: Optional[List[str]] = None,
    layer: Optional[str] = None,
    entity_type: Optional[str] = None,
) -> Dict[str, Any]:
    """Delete entities by handle list or layer/type filter."""
    return delete_entities(file_path, handles, layer, entity_type)


@mcp.tool()
def file_execute_ezdxf_script(script_code: str, target_file: Optional[str] = None) -> Dict[str, Any]:
    """Execute custom ezdxf Python code for parametric CAD generation."""
    return execute_ezdxf_script(script_code, target_file)


@mcp.tool()
def file_generate_scr(commands: List[str], output_path: str, comment: str = "Generated by CAD-FILE-MCP") -> Dict[str, Any]:
    """Generate an AutoCAD Script file (.scr) for batch execution."""
    return generate_scr_script(commands, output_path, comment)


@mcp.tool()
def file_generate_lisp(
    routine_name: str,
    custom_lisp_code: Optional[str] = None,
    template_type: Optional[str] = None,
    parameters: Optional[Dict[str, Any]] = None,
    output_path: Optional[str] = None,
) -> Dict[str, Any]:
    """Generate an AutoLISP routine (.lsp) file for AutoCAD."""
    return generate_autolisp_script(routine_name, custom_lisp_code, template_type, parameters, output_path)


def main():
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
